#!/usr/bin/env python3
"""Calculate zone centroids from GeoJSON and generate SQL updates.

This script reads zone polygons from a GeoJSON file, calculates their centroids,
and outputs:
1. CSV file with zone_id, center_lat, center_lon
2. SQL statements to update gold.dim_zones table

The script handles both Polygon and MultiPolygon geometries using shapely.
"""

import csv
import json
from pathlib import Path
from typing import List, Tuple

from shapely.geometry import shape


def load_geojson(file_path: Path) -> dict:
    """Load and parse GeoJSON file.

    Args:
        file_path: Path to the GeoJSON file

    Returns:
        Parsed GeoJSON data as dictionary

    Raises:
        FileNotFoundError: If the GeoJSON file doesn't exist
        json.JSONDecodeError: If the file is not valid JSON
    """
    if not file_path.exists():
        raise FileNotFoundError(f"GeoJSON file not found: {file_path}")

    with open(file_path, "r", encoding="utf-8") as f:
        return json.load(f)


def calculate_centroid(geometry: dict) -> Tuple[float, float]:
    """Calculate the centroid of a GeoJSON geometry.

    Args:
        geometry: GeoJSON geometry object (Polygon or MultiPolygon)

    Returns:
        Tuple of (latitude, longitude) for the centroid

    Raises:
        ValueError: If geometry type is not supported
    """
    geom = shape(geometry)
    centroid = geom.centroid
    # Return as (lat, lon) - note that shapely uses (x, y) which is (lon, lat)
    return (centroid.y, centroid.x)


def process_zones(geojson_data: dict) -> List[Tuple[str, float, float]]:
    """Process all zones and calculate their centroids.

    Args:
        geojson_data: Parsed GeoJSON FeatureCollection

    Returns:
        List of tuples containing (zone_id, center_lat, center_lon)
    """
    zones = []

    if geojson_data.get("type") != "FeatureCollection":
        raise ValueError("GeoJSON must be a FeatureCollection")

    for feature in geojson_data.get("features", []):
        properties = feature.get("properties", {})
        geometry = feature.get("geometry")

        if not geometry:
            print("Warning: Feature missing geometry, skipping")
            continue

        zone_id = properties.get("zone_id")
        if not zone_id:
            print("Warning: Feature missing zone_id, skipping")
            continue

        try:
            center_lat, center_lon = calculate_centroid(geometry)
            zones.append((zone_id, center_lat, center_lon))
        except Exception as e:
            print(f"Error processing zone {zone_id}: {e}")
            continue

    # Sort by zone_id for consistent output
    zones.sort(key=lambda x: x[0])
    return zones


def write_csv(zones: List[Tuple[str, float, float]], output_path: Path) -> None:
    """Write zone centroids to CSV file.

    Args:
        zones: List of (zone_id, center_lat, center_lon) tuples
        output_path: Path to output CSV file
    """
    output_path.parent.mkdir(parents=True, exist_ok=True)

    with open(output_path, "w", encoding="utf-8", newline="") as f:
        writer = csv.writer(f)
        writer.writerow(["zone_id", "center_lat", "center_lon"])
        for zone_id, center_lat, center_lon in zones:
            writer.writerow([zone_id, f"{center_lat:.6f}", f"{center_lon:.6f}"])

    print(f"CSV written to: {output_path}")


def write_sql(zones: List[Tuple[str, float, float]], output_path: Path) -> None:
    """Write SQL UPDATE statements for dim_zones table.

    Args:
        zones: List of (zone_id, center_lat, center_lon) tuples
        output_path: Path to output SQL file
    """
    output_path.parent.mkdir(parents=True, exist_ok=True)

    with open(output_path, "w", encoding="utf-8") as f:
        f.write("-- Update dim_zones with zone centroids calculated from GeoJSON\n")
        f.write("-- Generated by calculate_zone_centroids.py\n")
        f.write("--\n")
        f.write("-- First, add columns if they don't exist (run manually if needed):\n")
        f.write(
            "-- ALTER TABLE gold.dim_zones ADD COLUMNS (center_lat DOUBLE, center_lon DOUBLE);\n"
        )
        f.write("\n")

        for zone_id, center_lat, center_lon in zones:
            sql = (
                f"UPDATE gold.dim_zones "
                f"SET center_lat = {center_lat:.6f}, center_lon = {center_lon:.6f} "
                f"WHERE zone_id = '{zone_id}';\n"
            )
            f.write(sql)

    print(f"SQL written to: {output_path}")


def main() -> None:
    """Main function to orchestrate centroid calculation and output generation."""
    # Determine paths relative to this script
    script_dir = Path(__file__).parent.resolve()
    repo_root = script_dir.parent.parent.parent

    # Input: GeoJSON file
    geojson_path = repo_root / "data" / "sao-paulo" / "zones.geojson"

    # Output directory
    output_dir = script_dir / "output"
    csv_output = output_dir / "zone_centroids.csv"
    sql_output = output_dir / "update_dim_zones_centroids.sql"

    print("Zone Centroid Calculator")
    print("=" * 50)
    print(f"Input GeoJSON: {geojson_path}")
    print(f"Output CSV: {csv_output}")
    print(f"Output SQL: {sql_output}")
    print()

    # Load GeoJSON
    print("Loading GeoJSON...")
    geojson_data = load_geojson(geojson_path)

    # Process zones
    print("Calculating centroids...")
    zones = process_zones(geojson_data)
    print(f"Processed {len(zones)} zones")
    print()

    # Write outputs
    print("Writing outputs...")
    write_csv(zones, csv_output)
    write_sql(zones, sql_output)
    print()

    # Display summary
    print("Summary:")
    print(f"  Zones processed: {len(zones)}")
    print(f"  CSV records: {len(zones) + 1} (including header)")
    print(f"  SQL statements: {len(zones)}")
    print()
    print("Done!")


if __name__ == "__main__":
    main()
