from typing import Any

class Cursor:
    def execute(self, operation: str, parameters: Any = ...) -> None: ...
    def fetchone(self) -> tuple[Any, ...] | None: ...
    def fetchall(self) -> list[tuple[Any, ...]]: ...
    def fetchmany(self, size: int = ...) -> list[tuple[Any, ...]]: ...
    def close(self) -> None: ...
    @property
    def description(
        self,
    ) -> list[tuple[str, str, None, None, None, None, None]] | None: ...
    @property
    def rowcount(self) -> int: ...

class Connection:
    def __init__(
        self,
        host: str = ...,
        port: int = ...,
        scheme: str = ...,
        username: str | None = ...,
        password: str | None = ...,
        database: str = ...,
        auth: str | None = ...,
        configuration: dict[str, str] | None = ...,
        kerberos_service_name: str | None = ...,
        thrift_transport: Any = ...,
    ) -> None: ...
    def cursor(self) -> Cursor: ...
    def close(self) -> None: ...
    def commit(self) -> None: ...
    def rollback(self) -> None: ...
