version: 2

models:
  - name: stg_trips
    description: Staging model for trip events from Bronze layer.
    columns:
      - name: event_id
        tests:
          - unique
          - not_null
      - name: trip_id
        tests:
          - not_null
      - name: trip_state
        tests:
          - accepted_values:
              values: ['requested', 'offer_sent', 'offer_expired', 'offer_rejected', 'matched', 'driver_en_route', 'driver_arrived', 'started', 'completed', 'cancelled', 'no_drivers_available']

  - name: stg_gps_pings
    description: Staging model for GPS ping events from Bronze layer.
    columns:
      - name: event_id
        tests:
          - unique
          - not_null
      - name: entity_type
        tests:
          - accepted_values:
              values: ['driver', 'rider']
      - name: latitude
        tests:
          - dbt_utils.accepted_range:
              min_value: -23.8
              max_value: -23.3
              inclusive: true
      - name: longitude
        tests:
          - dbt_utils.accepted_range:
              min_value: -46.9
              max_value: -46.3
              inclusive: true

  - name: stg_driver_status
    description: Staging model for driver status change events from Bronze layer.
    columns:
      - name: event_id
        tests:
          - unique
          - not_null
      - name: new_status
        tests:
          - accepted_values:
              values: ['online', 'offline', 'en_route_pickup', 'en_route_destination']

  - name: stg_surge_updates
    description: Staging model for surge pricing update events from Bronze layer.
    columns:
      - name: event_id
        tests:
          - unique
          - not_null

  - name: stg_ratings
    description: Staging model for rating events from Bronze layer.
    columns:
      - name: event_id
        tests:
          - unique
          - not_null
      - name: rating
        tests:
          - accepted_values:
              values: [1, 2, 3, 4, 5]

  - name: stg_payments
    description: Staging model for payment events from Bronze layer.
    columns:
      - name: event_id
        tests:
          - unique
          - not_null

  - name: stg_drivers
    description: Staging model for driver profile events from Bronze layer.
    columns:
      - name: event_id
        tests:
          - unique
          - not_null

  - name: stg_riders
    description: Staging model for rider profile events from Bronze layer.
    columns:
      - name: event_id
        tests:
          - unique
          - not_null
