name: 'rideshare'
version: '1.0.0'
config-version: 2

profile: 'rideshare'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  rideshare:
    staging:
      +schema: silver
      +materialized: incremental
      +on_schema_change: fail
      +incremental_strategy: merge
      +tags:
        - silver
    marts:
      +file_format: delta
      dimensions:
        +schema: gold
        +materialized: table
        +tags:
          - gold
          - dimensions
      facts:
        +schema: gold
        +materialized: table
        +tags:
          - gold
          - facts
      aggregates:
        +schema: gold
        +materialized: table
        +tags:
          - gold
          - aggregates
