rideshare:
  target: dev
  outputs:
    dev:
      type: spark
      method: thrift
      host: spark-thrift-server
      port: 10000
      schema: default
      threads: 1
      connect_timeout: 60
      connect_retries: 3
      auth: NOSASL
