version: 2

models:
  - name: dim_drivers
    description: Driver dimension with SCD Type 2 tracking profile changes.
    tests:
      - scd_validity:
          driver_id_column: driver_id
    columns:
      - name: driver_key
        tests:
          - unique
          - not_null

  - name: dim_riders
    description: Rider dimension with current state only.
    columns:
      - name: rider_key
        tests:
          - unique
          - not_null
      - name: rider_id
        tests:
          - unique

  - name: dim_zones
    description: Geographic zones dimension (static reference).
    columns:
      - name: zone_key
        tests:
          - unique
          - not_null
      - name: zone_id
        tests:
          - unique

  - name: dim_time
    description: Time dimension with date attributes.
    columns:
      - name: time_key
        tests:
          - unique
          - not_null

  - name: dim_payment_methods
    description: Payment methods dimension with SCD Type 2.
    tests:
      - scd_validity:
          driver_id_column: payment_method_id
    columns:
      - name: payment_method_key
        tests:
          - unique
          - not_null
