from typing import Any

class Connection:
    def cursor(self) -> Cursor: ...
    def close(self) -> None: ...

class Cursor:
    def execute(self, operation: str, parameters: Any = ...) -> None: ...
    def fetchone(self) -> tuple[Any, ...] | None: ...
    def fetchall(self) -> list[tuple[Any, ...]]: ...
    def close(self) -> None: ...

def connect(
    host: str = ...,
    port: int = ...,
    auth: str = ...,
    database: str = ...,
    username: str = ...,
    password: str = ...,
    configuration: dict[str, str] = ...,
) -> Connection: ...
