version: 2

models:
  - name: agg_hourly_zone_demand
    description: Hourly demand and supply metrics by zone.
    columns:
      - name: zone_key
        tests:
          - not_null
          - relationships:
              to: ref('dim_zones')
              field: zone_key
    tests:
      - dbt_utils.expression_is_true:
          expression: "completed_trips <= requested_trips"
          name: completed_lte_requested
      - dbt_utils.expression_is_true:
          expression: "completion_rate between 0.0 and 1.0"
          name: completion_rate_range

  - name: agg_daily_driver_performance
    description: Daily driver KPIs including idle time and earnings.
    columns:
      - name: driver_key
        tests:
          - not_null
          - relationships:
              to: ref('dim_drivers')
              field: driver_key
      - name: time_key
        tests:
          - not_null
          - relationships:
              to: ref('dim_time')
              field: time_key
    tests:
      - dbt_utils.expression_is_true:
          expression: "idle_pct between 0.0 and 100.0"
          name: idle_range
      - dbt_utils.expression_is_true:
          expression: "en_route_minutes + on_trip_minutes <= online_minutes"
          name: time_consistency

  - name: agg_daily_platform_revenue
    description: Daily revenue and fees by zone.
    columns:
      - name: zone_key
        tests:
          - not_null
          - relationships:
              to: ref('dim_zones')
              field: zone_key
      - name: time_key
        tests:
          - not_null
          - relationships:
              to: ref('dim_time')
              field: time_key
    tests:
      - dbt_utils.expression_is_true:
          expression: "abs(total_platform_fees + total_driver_payouts - total_revenue) < 0.01"
          name: splits_sum_to_total

  - name: agg_surge_history
    description: Surge pricing trends over time by zone.
    columns:
      - name: zone_key
        tests:
          - not_null
          - relationships:
              to: ref('dim_zones')
              field: zone_key
