version: 2

models:
  - name: fact_trips
    description: Completed trips with fare metrics and journey details.
    columns:
      - name: trip_key
        tests:
          - unique
      - name: trip_id
        tests:
          - unique
      - name: driver_key
        tests:
          - relationships:
              to: ref('dim_drivers')
              field: driver_key
      - name: rider_key
        tests:
          - relationships:
              to: ref('dim_riders')
              field: rider_key
      - name: pickup_zone_key
        tests:
          - relationships:
              to: ref('dim_zones')
              field: zone_key
      - name: dropoff_zone_key
        tests:
          - relationships:
              to: ref('dim_zones')
              field: zone_key
      - name: time_key
        tests:
          - relationships:
              to: ref('dim_time')
              field: time_key
      - name: trip_state
        tests:
          - accepted_values:
              values: ['completed']

  - name: fact_payments
    description: Payment transactions with fare breakdown.
    tests:
      - fee_percentage:
          total_column: total_fare
          fee_column: platform_fee
          expected_percentage: 0.25
      - fee_percentage:
          total_column: total_fare
          fee_column: driver_payout
          expected_percentage: 0.75
    columns:
      - name: payment_key
        tests:
          - unique
      - name: payment_id
        tests:
          - unique
      - name: trip_key
        tests:
          - relationships:
              to: ref('fact_trips')
              field: trip_key
      - name: rider_key
        tests:
          - relationships:
              to: ref('dim_riders')
              field: rider_key
      - name: driver_key
        tests:
          - relationships:
              to: ref('dim_drivers')
              field: driver_key
      - name: time_key
        tests:
          - relationships:
              to: ref('dim_time')
              field: time_key

  - name: fact_ratings
    description: Individual ratings with rater and ratee information.
    columns:
      - name: rating_key
        tests:
          - unique
      - name: trip_key
        tests:
          - relationships:
              to: ref('fact_trips')
              field: trip_key
      - name: time_key
        tests:
          - relationships:
              to: ref('dim_time')
              field: time_key
      - name: rating
        tests:
          - accepted_values:
              values: [1, 2, 3, 4, 5]

  - name: fact_cancellations
    description: Cancelled trips with cancellation details.
    columns:
      - name: cancellation_key
        tests:
          - unique
      - name: trip_id
        tests:
          - unique
      - name: rider_key
        tests:
          - relationships:
              to: ref('dim_riders')
              field: rider_key
      - name: pickup_zone_key
        tests:
          - relationships:
              to: ref('dim_zones')
              field: zone_key
      - name: time_key
        tests:
          - relationships:
              to: ref('dim_time')
              field: time_key

  - name: fact_driver_activity
    description: Driver status durations for utilization analysis.
    columns:
      - name: activity_key
        tests:
          - unique
      - name: driver_key
        tests:
          - relationships:
              to: ref('dim_drivers')
              field: driver_key
      - name: time_key
        tests:
          - relationships:
              to: ref('dim_time')
              field: time_key
