apiVersion: v1
kind: ConfigMap
metadata:
  name: trino-config-glue
  labels:
    app: trino
data:
  config.properties: |
    coordinator=true
    node-scheduler.include-coordinator=true
    http-server.http.port=8080
    discovery.uri=http://localhost:8080
    http-server.authentication.type=PASSWORD
    event-listener.config-files=/etc/trino/event-listener.properties

  jvm.config: |
    -server
    -Xmx2G
    -XX:+UseG1GC
    -XX:G1HeapRegionSize=32M
    -XX:+ExplicitGCInvokesConcurrent
    -XX:+HeapDumpOnOutOfMemoryError
    -XX:+ExitOnOutOfMemoryError
    -XX:ReservedCodeCacheSize=256M
    -XX:+UnlockDiagnosticVMOptions
    -XX:G1NumCollectionsKeepPinned=10000000
    -Djdk.attach.allowAttachSelf=true
    -Djdk.nio.maxCachedBufferSize=2000000

  node.properties: |
    node.environment=kubernetes
    node.id=trino-coordinator
    node.data-dir=/data/trino

  delta.properties.template: |
    connector.name=delta_lake
    hive.metastore=glue
    hive.metastore.glue.region=us-east-1
    hive.s3.path-style-access=false
    hive.s3.region=us-east-1
    delta.enable-non-concurrent-writes=true
    delta.register-table-procedure.enabled=true

  password-authenticator.properties: |
    password-authenticator.name=file
    file.password-file=/etc/trino/password.db
    file.refresh-period=5s

  access-control.properties: |
    access-control.name=file
    security.config-file=/etc/trino/rules.json
    security.refresh-period=60s

  password.db.template: |
    admin:${TRINO_ADMIN_PASSWORD_HASH}
    visitor:${TRINO_VISITOR_PASSWORD_HASH}

  rules.json: |
    {
      "catalogs": [
        {
          "user": "admin",
          "catalog": ".*",
          "allow": "all"
        },
        {
          "user": ".*",
          "catalog": "system",
          "allow": "none"
        },
        {
          "user": ".*",
          "catalog": "delta",
          "allow": "read-only"
        },
        {
          "user": ".*",
          "catalog": ".*",
          "allow": "read-only"
        }
      ]
    }

  event-listener.properties: |
    event-listener.name=query-event-listener
    query-event-listener.log-completed-queries=true
