def latlng_to_cell(lat: float, lng: float, res: int) -> str: ...
def cell_to_latlng(cell: str) -> tuple[float, float]: ...
def grid_disk(origin: str, k: int) -> list[str]: ...
def cell_to_boundary(cell: str) -> tuple[tuple[float, float], ...]: ...
def cell_area(cell: str, unit: str = ...) -> float: ...
def great_circle_distance(
    latlng1: tuple[float, float], latlng2: tuple[float, float], unit: str = ...
) -> float: ...
