version: 2

models:
  - name: stg_trips
    description: |
      Staging model for trip events from Bronze layer.
      Parses trip_state from event_type, deduplicates by event_id,
      validates state transitions, and standardizes timestamps to UTC.
    columns:
      - name: event_id
        description: Unique identifier for the event
        tests:
          - unique
          - not_null

      - name: event_type
        description: Type of trip event (e.g., trip.requested, trip.matched)
        tests:
          - not_null

      - name: trip_state
        description: Parsed trip state from event_type
        tests:
          - not_null
          - accepted_values:
              values:
                - 'requested'
                - 'offer_sent'
                - 'offer_expired'
                - 'offer_rejected'
                - 'matched'
                - 'driver_en_route'
                - 'driver_arrived'
                - 'started'
                - 'completed'
                - 'cancelled'

      - name: timestamp
        description: Event timestamp in UTC
        tests:
          - not_null

      - name: trip_id
        description: Unique identifier for the trip
        tests:
          - not_null

      - name: rider_id
        description: Unique identifier for the rider
        tests:
          - not_null

      - name: pickup_lat
        description: Pickup location latitude
        tests:
          - not_null

      - name: pickup_lon
        description: Pickup location longitude
        tests:
          - not_null

      - name: dropoff_lat
        description: Dropoff location latitude
        tests:
          - not_null

      - name: dropoff_lon
        description: Dropoff location longitude
        tests:
          - not_null

      - name: pickup_zone_id
        description: Zone identifier for pickup location
        tests:
          - not_null

      - name: dropoff_zone_id
        description: Zone identifier for dropoff location
        tests:
          - not_null

      - name: surge_multiplier
        description: Surge pricing multiplier applied to fare
        tests:
          - not_null

      - name: fare
        description: Total fare amount for the trip
        tests:
          - not_null

      - name: driver_id
        description: Unique identifier for the driver (nullable for early states)

      - name: _ingested_at
        description: Timestamp when record was ingested into Bronze layer
        tests:
          - not_null

  - name: stg_gps_pings
    description: |
      Staging model for GPS ping events from Bronze layer.
      Parses location coordinates, validates Sao Paulo bounds,
      deduplicates by event_id, and standardizes timestamps.
    columns:
      - name: event_id
        description: Unique identifier for the GPS ping event
        tests:
          - unique
          - not_null

      - name: entity_type
        description: Type of entity (driver or rider)
        tests:
          - not_null
          - accepted_values:
              values:
                - 'driver'
                - 'rider'

      - name: entity_id
        description: Unique identifier for the entity
        tests:
          - not_null

      - name: timestamp
        description: GPS ping timestamp in UTC
        tests:
          - not_null

      - name: latitude
        description: GPS latitude coordinate
        tests:
          - not_null
          - dbt_utils.accepted_range:
              arguments:
                min_value: -23.8
                max_value: -23.3
                inclusive: true

      - name: longitude
        description: GPS longitude coordinate
        tests:
          - not_null
          - dbt_utils.accepted_range:
              arguments:
                min_value: -46.9
                max_value: -46.3
                inclusive: true

      - name: accuracy
        description: GPS accuracy in meters
        tests:
          - not_null

      - name: heading
        description: Direction of travel in degrees

      - name: speed
        description: Speed in meters per second

      - name: trip_id
        description: Associated trip ID (if GPS ping during trip)

      - name: trip_state
        description: Current trip state (if GPS ping during trip)

      - name: _ingested_at
        description: Timestamp when record was ingested into Bronze layer
        tests:
          - not_null

  - name: stg_driver_status
    description: |
      Staging model for driver status change events from Bronze layer.
      Parses location coordinates, validates status enum values,
      deduplicates by event_id, and standardizes timestamps.
    columns:
      - name: event_id
        description: Unique identifier for the status change event
        tests:
          - unique
          - not_null

      - name: driver_id
        description: Unique identifier for the driver
        tests:
          - not_null

      - name: timestamp
        description: Status change timestamp in UTC
        tests:
          - not_null

      - name: new_status
        description: New driver status
        tests:
          - not_null
          - accepted_values:
              values:
                - 'idle'
                - 'dispatched'
                - 'en_route_to_pickup'
                - 'arrived_at_pickup'
                - 'on_trip'
                - 'offline'

      - name: previous_status
        description: Previous driver status (nullable for first event)

      - name: trigger
        description: Reason for status change
        tests:
          - not_null

      - name: latitude
        description: Driver latitude at status change
        tests:
          - not_null

      - name: longitude
        description: Driver longitude at status change
        tests:
          - not_null

      - name: _ingested_at
        description: Timestamp when record was ingested into Bronze layer
        tests:
          - not_null

  - name: stg_surge_updates
    description: |
      Staging model for surge pricing update events from Bronze layer.
      Validates multiplier ranges (1.0 - 2.5), deduplicates by event_id,
      and standardizes timestamps to UTC.
    columns:
      - name: event_id
        description: Unique identifier for the surge update event
        tests:
          - unique
          - not_null

      - name: zone_id
        description: Zone identifier for surge update
        tests:
          - not_null

      - name: timestamp
        description: Surge update timestamp in UTC
        tests:
          - not_null

      - name: previous_multiplier
        description: Previous surge multiplier
        tests:
          - not_null
          - dbt_utils.accepted_range:
              arguments:
                min_value: 1.0
                max_value: 2.5
                inclusive: true

      - name: new_multiplier
        description: New surge multiplier
        tests:
          - not_null
          - dbt_utils.accepted_range:
              arguments:
                min_value: 1.0
                max_value: 2.5
                inclusive: true

      - name: available_drivers
        description: Number of available drivers in zone
        tests:
          - not_null

      - name: pending_requests
        description: Number of pending ride requests in zone
        tests:
          - not_null

      - name: calculation_window_seconds
        description: Time window used for surge calculation

      - name: _ingested_at
        description: Timestamp when record was ingested into Bronze layer
        tests:
          - not_null
