version: 2

models:
  - name: stg_trips
    description: |
      Staging model for trip events from Bronze layer.
      Parses trip_state from event_type, deduplicates by event_id,
      validates state transitions, and standardizes timestamps to UTC.

      {{ doc('incremental_strategy') }}
    columns:
      - name: event_id
        description: Unique identifier for the event
        tests:
          - unique
          - not_null

      - name: event_type
        description: Type of trip event (e.g., trip.requested, trip.matched)
        tests:
          - not_null

      - name: trip_state
        description: Parsed trip state from event_type
        tests:
          - not_null
          - accepted_values:
              values:
                - 'requested'
                - 'offer_sent'
                - 'offer_expired'
                - 'offer_rejected'
                - 'matched'
                - 'driver_en_route'
                - 'driver_arrived'
                - 'started'
                - 'completed'
                - 'cancelled'

      - name: timestamp
        description: Event timestamp in UTC
        tests:
          - not_null
          - no_future_dates

      - name: trip_id
        description: Unique identifier for the trip
        tests:
          - not_null

      - name: rider_id
        description: Unique identifier for the rider
        tests:
          - not_null

      - name: pickup_lat
        description: Pickup location latitude
        tests:
          - not_null

      - name: pickup_lon
        description: Pickup location longitude
        tests:
          - not_null

      - name: dropoff_lat
        description: Dropoff location latitude
        tests:
          - not_null

      - name: dropoff_lon
        description: Dropoff location longitude
        tests:
          - not_null

      - name: pickup_zone_id
        description: Zone identifier for pickup location
        tests:
          - not_null

      - name: dropoff_zone_id
        description: Zone identifier for dropoff location
        tests:
          - not_null

      - name: surge_multiplier
        description: Surge pricing multiplier applied to fare
        tests:
          - not_null

      - name: fare
        description: Total fare amount for the trip
        tests:
          - not_null

      - name: driver_id
        description: Unique identifier for the driver (nullable for early states)

      - name: _ingested_at
        description: Timestamp when record was ingested into Bronze layer
        tests:
          - not_null

  - name: stg_gps_pings
    description: |
      Staging model for GPS ping events from Bronze layer.
      Parses location coordinates, validates Sao Paulo bounds,
      deduplicates by event_id, and standardizes timestamps.
    columns:
      - name: event_id
        description: Unique identifier for the GPS ping event
        tests:
          - unique
          - not_null

      - name: entity_type
        description: Type of entity (driver or rider)
        tests:
          - not_null
          - accepted_values:
              values:
                - 'driver'
                - 'rider'

      - name: entity_id
        description: Unique identifier for the entity
        tests:
          - not_null

      - name: timestamp
        description: GPS ping timestamp in UTC
        tests:
          - not_null
          - no_future_dates

      - name: latitude
        description: GPS latitude coordinate
        tests:
          - not_null
          - dbt_utils.accepted_range:
              arguments:
                min_value: -23.8
                max_value: -23.3
                inclusive: true

      - name: longitude
        description: GPS longitude coordinate
        tests:
          - not_null
          - dbt_utils.accepted_range:
              arguments:
                min_value: -46.9
                max_value: -46.3
                inclusive: true

      - name: accuracy
        description: GPS accuracy in meters
        tests:
          - not_null

      - name: heading
        description: Direction of travel in degrees

      - name: speed
        description: Speed in meters per second

      - name: trip_id
        description: Associated trip ID (if GPS ping during trip)

      - name: trip_state
        description: Current trip state (if GPS ping during trip)

      - name: _ingested_at
        description: Timestamp when record was ingested into Bronze layer
        tests:
          - not_null

  - name: stg_driver_status
    description: |
      Staging model for driver status change events from Bronze layer.
      Parses location coordinates, validates status enum values,
      deduplicates by event_id, and standardizes timestamps.
    columns:
      - name: event_id
        description: Unique identifier for the status change event
        tests:
          - unique
          - not_null

      - name: driver_id
        description: Unique identifier for the driver
        tests:
          - not_null

      - name: timestamp
        description: Status change timestamp in UTC
        tests:
          - not_null
          - no_future_dates

      - name: new_status
        description: New driver status
        tests:
          - not_null
          - accepted_values:
              values:
                - 'idle'
                - 'dispatched'
                - 'en_route_to_pickup'
                - 'arrived_at_pickup'
                - 'on_trip'
                - 'offline'

      - name: previous_status
        description: Previous driver status (nullable for first event)

      - name: trigger
        description: Reason for status change
        tests:
          - not_null

      - name: latitude
        description: Driver latitude at status change
        tests:
          - not_null

      - name: longitude
        description: Driver longitude at status change
        tests:
          - not_null

      - name: _ingested_at
        description: Timestamp when record was ingested into Bronze layer
        tests:
          - not_null

  - name: stg_surge_updates
    description: |
      Staging model for surge pricing update events from Bronze layer.
      Validates multiplier ranges (1.0 - 2.5), deduplicates by event_id,
      and standardizes timestamps to UTC.
    columns:
      - name: event_id
        description: Unique identifier for the surge update event
        tests:
          - unique
          - not_null

      - name: zone_id
        description: Zone identifier for surge update
        tests:
          - not_null

      - name: timestamp
        description: Surge update timestamp in UTC
        tests:
          - not_null
          - no_future_dates

      - name: previous_multiplier
        description: Previous surge multiplier
        tests:
          - not_null
          - dbt_utils.accepted_range:
              arguments:
                min_value: 1.0
                max_value: 2.5
                inclusive: true

      - name: new_multiplier
        description: New surge multiplier
        tests:
          - not_null
          - dbt_utils.accepted_range:
              arguments:
                min_value: 1.0
                max_value: 2.5
                inclusive: true

      - name: available_drivers
        description: Number of available drivers in zone
        tests:
          - not_null

      - name: pending_requests
        description: Number of pending ride requests in zone
        tests:
          - not_null

      - name: calculation_window_seconds
        description: Time window used for surge calculation

      - name: _ingested_at
        description: Timestamp when record was ingested into Bronze layer
        tests:
          - not_null

  - name: stg_ratings
    description: |
      Staging model for rating events from Bronze layer.
      Validates rating range (1-5), deduplicates by event_id,
      and standardizes timestamps to UTC.
    columns:
      - name: event_id
        description: Unique identifier for the rating event
        tests:
          - unique
          - not_null

      - name: trip_id
        description: Unique identifier for the trip being rated
        tests:
          - not_null

      - name: timestamp
        description: Rating timestamp in UTC
        tests:
          - not_null
          - no_future_dates

      - name: rater_type
        description: Type of entity providing the rating (driver or rider)
        tests:
          - not_null
          - accepted_values:
              values:
                - 'driver'
                - 'rider'

      - name: rater_id
        description: Unique identifier for the rater
        tests:
          - not_null

      - name: ratee_type
        description: Type of entity receiving the rating (driver or rider)
        tests:
          - not_null
          - accepted_values:
              values:
                - 'driver'
                - 'rider'

      - name: ratee_id
        description: Unique identifier for the ratee
        tests:
          - not_null

      - name: rating
        description: Rating value between 1 and 5
        tests:
          - not_null
          - accepted_values:
              values: [1, 2, 3, 4, 5]

      - name: _ingested_at
        description: Timestamp when record was ingested into Bronze layer
        tests:
          - not_null

  - name: stg_payments
    description: |
      Staging model for payment events from Bronze layer.
      Validates positive amounts, calculates platform fees and driver payouts,
      deduplicates by event_id, and standardizes timestamps to UTC.
    columns:
      - name: event_id
        description: Unique identifier for the payment event
        tests:
          - unique
          - not_null

      - name: payment_id
        description: Unique identifier for the payment transaction
        tests:
          - not_null

      - name: trip_id
        description: Unique identifier for the trip
        tests:
          - not_null

      - name: timestamp
        description: Payment timestamp in UTC
        tests:
          - not_null
          - no_future_dates

      - name: rider_id
        description: Unique identifier for the rider
        tests:
          - not_null

      - name: driver_id
        description: Unique identifier for the driver
        tests:
          - not_null

      - name: payment_method_type
        description: Type of payment method (credit_card, debit_card, etc.)
        tests:
          - not_null

      - name: payment_method_masked
        description: Masked payment method identifier
        tests:
          - not_null

      - name: fare_amount
        description: Total fare amount
        tests:
          - not_null
          - dbt_utils.accepted_range:
              arguments:
                min_value: 0
                inclusive: false

      - name: platform_fee_percentage
        description: Platform fee percentage (typically 0.25 for 25%)
        tests:
          - not_null

      - name: platform_fee_amount
        description: Platform fee amount in BRL
        tests:
          - not_null
          - dbt_utils.accepted_range:
              arguments:
                min_value: 0
                inclusive: false

      - name: driver_payout_amount
        description: Driver payout amount in BRL
        tests:
          - not_null
          - dbt_utils.accepted_range:
              arguments:
                min_value: 0
                inclusive: false

      - name: _ingested_at
        description: Timestamp when record was ingested into Bronze layer
        tests:
          - not_null

  - name: stg_drivers
    description: |
      Staging model for driver profile events from Bronze layer.
      Captures create and update events for SCD Type 2 tracking,
      deduplicates by event_id, and standardizes timestamps to UTC.
    columns:
      - name: event_id
        description: Unique identifier for the profile event
        tests:
          - unique
          - not_null

      - name: event_type
        description: Type of profile event (driver.profile_created or driver.profile_updated)
        tests:
          - not_null
          - accepted_values:
              values:
                - 'driver.profile_created'
                - 'driver.profile_updated'

      - name: driver_id
        description: Unique identifier for the driver
        tests:
          - not_null

      - name: timestamp
        description: Profile event timestamp in UTC
        tests:
          - not_null
          - no_future_dates

      - name: first_name
        description: Driver first name
        tests:
          - not_null

      - name: last_name
        description: Driver last name
        tests:
          - not_null

      - name: email
        description: Driver email address
        tests:
          - not_null

      - name: phone
        description: Driver phone number
        tests:
          - not_null

      - name: home_lat
        description: Driver home location latitude
        tests:
          - not_null

      - name: home_lon
        description: Driver home location longitude
        tests:
          - not_null

      - name: preferred_zones
        description: JSON array of preferred zone IDs
        tests:
          - not_null

      - name: shift_preference
        description: Preferred shift timing
        tests:
          - not_null

      - name: vehicle_make
        description: Vehicle manufacturer
        tests:
          - not_null

      - name: vehicle_model
        description: Vehicle model
        tests:
          - not_null

      - name: vehicle_year
        description: Vehicle year
        tests:
          - not_null

      - name: license_plate
        description: Vehicle license plate
        tests:
          - not_null

      - name: _ingested_at
        description: Timestamp when record was ingested into Bronze layer
        tests:
          - not_null

  - name: stg_riders
    description: |
      Staging model for rider profile events from Bronze layer.
      Captures create and update events for current state tracking,
      deduplicates by event_id, and standardizes timestamps to UTC.
    columns:
      - name: event_id
        description: Unique identifier for the profile event
        tests:
          - unique
          - not_null

      - name: event_type
        description: Type of profile event (rider.profile_created or rider.profile_updated)
        tests:
          - not_null
          - accepted_values:
              values:
                - 'rider.profile_created'
                - 'rider.profile_updated'

      - name: rider_id
        description: Unique identifier for the rider
        tests:
          - not_null

      - name: timestamp
        description: Profile event timestamp in UTC
        tests:
          - not_null
          - no_future_dates

      - name: first_name
        description: Rider first name
        tests:
          - not_null

      - name: last_name
        description: Rider last name
        tests:
          - not_null

      - name: email
        description: Rider email address
        tests:
          - not_null

      - name: phone
        description: Rider phone number
        tests:
          - not_null

      - name: home_lat
        description: Rider home location latitude
        tests:
          - not_null

      - name: home_lon
        description: Rider home location longitude
        tests:
          - not_null

      - name: payment_method_type
        description: Type of payment method
        tests:
          - not_null

      - name: payment_method_masked
        description: Masked payment method identifier
        tests:
          - not_null

      - name: behavior_factor
        description: Rider behavior factor (nullable)

      - name: _ingested_at
        description: Timestamp when record was ingested into Bronze layer
        tests:
          - not_null
